### PR TITLE
implement is_in_interval to pass test test_rectangle_contains_exact()

### PR DESCRIPTION
**Pull request by Pinku-Neko**

### CODE REVIEW

**Review by mgemaakbar — CHANGES_REQUESTED** [review]
Please fix conflict

**Review by mgemaakbar — CHANGES_REQUESTED** [review]
please remove unneeded import

**Review by mgemaakbar — APPROVED** [review]
LGTM

**Review by mgemaakbar — APPROVED** [review]

**Comment by Pinku-Neko** [comment]
bad

**Pull request closed without merging**
